version: "3.8"
services:
  rabbitmq:
    build:
      context: rabbitmq
      dockerfile: Dockerfile
    ports:
      - 5672:5672
      - 15672:15672
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025